# Form implementation generated from reading ui file 'd:\dev\1b_gui_app\pyqt_libms\login.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 300)
        font = QtGui.QFont()
        font.setPointSize(18)
        Form.setFont(font)
        self.btn_login_from_login = QtWidgets.QPushButton(Form)
        self.btn_login_from_login.setGeometry(QtCore.QRect(190, 220, 151, 41))
        self.btn_login_from_login.setObjectName("btn_login_from_login")
        self.login_form_username = QtWidgets.QLineEdit(Form)
        self.login_form_username.setGeometry(QtCore.QRect(142, 50, 241, 41))
        self.login_form_username.setObjectName("login_form_username")
        self.login_form_password = QtWidgets.QLineEdit(Form)
        self.login_form_password.setGeometry(QtCore.QRect(140, 110, 241, 41))
        self.login_form_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_form_password.setObjectName("login_form_password")
        self.login_error_message = QtWidgets.QLabel(Form)
        self.login_error_message.setGeometry(QtCore.QRect(140, 170, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_error_message.setFont(font)
        self.login_error_message.setStyleSheet("color: rgb(255, 0, 0);")
        self.login_error_message.setText("")
        self.login_error_message.setObjectName("login_error_message")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Form"))
        self.btn_login_from_login.setText(_translate("Form", "Login"))
        self.login_form_username.setPlaceholderText(_translate("Form", "Enter user name"))
        self.login_form_password.setPlaceholderText(_translate("Form", "Enter password"))
